- name: app setup
  ansible.builtin.import_role:
    name: common                    # the name indicates main role which we import that task here it is common is one-more role which app-setup.yaml is defined.
    tasks_from: app-setup.yaml      # this tasks_from indictaes which yaml file need to import the tasks 

- name: install maven
  ansible.builtin.dnf:
     name: maven 
     state: present

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:                   # here the args telling to asnisble run the command after Change the directory to /app and run mvn clean pacakge
    chdir: /app

- name: install dependencies
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
  args:               # here the args telling to asnisble run the command after Change the directory to /app and run mv target/shipping-1.0.jar shipping.jar 
    chdir: /app

- name: systemd setup
  ansible.builtin.import_role:
   name: common                    # the name indicates main role which we import that task here it is common is one-more role which systemd-setup.yaml is defined.
   tasks_from: systemd-setup.yaml

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes

- name: install mysql
  ansible.builtin.dnf:
    name: mysql 
    state: present

- name: install dependencies
  ansible.builtin.pip:
    name: "{{ item }}"        # here python module PyMySQL library is required to connect mysql client to load shipping data or schema
    executable: pip3.9        # here cryptography package is required to connect mysql client to connect with sha2_password authentication.
  loop:                     
    - cryptography
    - PyMySQL

- name: import shipping data
  community.mysql.mysql_db:
    state: import
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: RoboShop@1
    target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql
  
- name: start and enable shipping
  ansible.builtin.service:
    name: shipping
    state: restarted
    enabled: yes
