- name: call common role
  ansible.builtin.import_role:
    name: common
    tasks_from: include-vs-import.yaml   # here include-vs-import role is importing from common tasks in main roles section 
  when: os == "RedHat"

# - name: call common role
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: include-vs-import.yaml     # here include-vs-import role is including from common tasks in main roles section 